datasets:
  easvolee_pos:
    mzmine:
      template: "dda_orbitrap_pos"
      retention_time_range: [0.5, 31]
      approximate_feature_fwhm: 0.1
      minimum_feature_height: 5e4
      blank_subtraction:
        min_blank_presence: 3
        fold_change_threshold: 3
      spectral_library_files:
        - "msnlib/20250828_targetmol_hts_np_pos_ms2.json"
        - "msnlib/20241003_mcebio_pos_ms2.json"
        - "msnlib/20241003_otavapep_pos_ms2.json"
        - "msnlib/20241003_enamdisc_pos_ms2.json"
        - "msnlib/20241003_nihnp_pos_ms2.json"
        - "msnlib/20241003_mcescaf_pos_ms2.json"
        - "msnlib/20241003_mcedrug_pos_ms2.json"
        - "msnlib/20241003_enammol_pos_ms2.json"
        - "msnlib/20250828_mcediv_50k_sub_pos_ms2.json"
spectral_libraries:
  msnlib:
    zenodo_id: 16984129
